import { PortfolioItem, NavItem } from './types'

export const navItems: NavItem[] = [
  { label: 'About', href: '#about' },
  { label: 'Portfolio', href: '#portfolio' },
  { label: 'Contact', href: '#contact' },
]

export const portfolioItems: PortfolioItem[] = [
  // Digital
  {
    id: 'digital-1',
    title: 'Brand Launch Campaign',
    client: 'Lumina Beauty',
    category: 'Digital',
    description: 'Led comprehensive digital PR strategy for Lumina Beauty\'s product launch, securing coverage across 50+ digital publications and driving 2M+ impressions in the first week.',
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=800&fit=crop',
    results: ['50+ media placements', '2M+ impressions', '180% increase in web traffic'],
    year: 2024,
  },
  {
    id: 'digital-2',
    title: 'Crisis Communications',
    client: 'TechStart Inc.',
    category: 'Digital',
    description: 'Managed rapid response communications during product recall, minimizing brand damage through strategic messaging and proactive media outreach.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
    results: ['85% positive sentiment recovery', '24-hour response time', 'Featured in PR Week'],
    year: 2024,
  },
  {
    id: 'digital-3',
    title: 'SEO-Driven Press Strategy',
    client: 'GreenLeaf Wellness',
    category: 'Digital',
    description: 'Developed integrated PR and SEO campaign resulting in top-tier backlinks and significant organic search improvements.',
    thumbnail: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=600&fit=crop',
    results: ['25 DA70+ backlinks', '45% organic traffic increase', 'Page 1 rankings for key terms'],
    year: 2023,
  },
  // Print
  {
    id: 'print-1',
    title: 'Magazine Feature Story',
    client: 'Heritage Homes',
    category: 'Print',
    description: 'Secured 8-page spread in Architectural Digest featuring client\'s sustainable luxury home designs.',
    thumbnail: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=800&fit=crop',
    results: ['8-page feature spread', '500K+ print readership', '3 month lead time secured'],
    year: 2024,
  },
  {
    id: 'print-2',
    title: 'Trade Publication Campaign',
    client: 'InnovateTech',
    category: 'Print',
    description: 'Orchestrated thought leadership campaign resulting in bylined articles across major trade publications.',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=500&fit=crop',
    results: ['12 bylined articles', '4 cover stories', 'Industry award nomination'],
    year: 2023,
  },
  {
    id: 'print-3',
    title: 'Regional Press Tour',
    client: 'Artisan Spirits Co.',
    category: 'Print',
    description: 'Coordinated multi-city press tour generating coverage in regional lifestyle and food publications.',
    thumbnail: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&h=700&fit=crop',
    results: ['18 regional features', '6-city tour', '40+ journalist meetings'],
    year: 2023,
  },
  // Social
  {
    id: 'social-1',
    title: 'Viral TikTok Campaign',
    client: 'FreshFit Nutrition',
    category: 'Social',
    description: 'Created and executed TikTok-first content strategy that resulted in multiple viral moments and significant brand awareness lift.',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=800&fit=crop',
    embedType: 'tiktok',
    results: ['15M+ views', '3 viral videos', '200K new followers'],
    year: 2024,
  },
  {
    id: 'social-2',
    title: 'Instagram Rebranding',
    client: 'Bloom Florals',
    category: 'Social',
    description: 'Led complete Instagram visual identity overhaul, establishing cohesive aesthetic and increasing engagement rates.',
    thumbnail: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&h=600&fit=crop',
    embedType: 'instagram',
    results: ['250% engagement increase', '50K new followers', 'Featured on Instagram\'s @shop'],
    year: 2024,
  },
  {
    id: 'social-3',
    title: 'LinkedIn Thought Leadership',
    client: 'Executive Coaching Co.',
    category: 'Social',
    description: 'Developed and managed LinkedIn content strategy for C-suite client, positioning them as industry thought leader.',
    thumbnail: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=600&h=500&fit=crop',
    results: ['500K+ post impressions', '10K new connections', '5 speaking invitations'],
    year: 2023,
  },
  // Influencer Partnerships
  {
    id: 'influencer-1',
    title: 'Macro Influencer Campaign',
    client: 'LuxeStyle Fashion',
    category: 'Influencer Partnerships',
    description: 'Negotiated and managed partnerships with 5 macro influencers (1M+ followers each) for seasonal collection launch.',
    thumbnail: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&h=800&fit=crop',
    results: ['8M combined reach', '$450K earned media value', '15% sales increase'],
    year: 2024,
  },
  {
    id: 'influencer-2',
    title: 'Micro-Influencer Program',
    client: 'Honest Kitchen',
    category: 'Influencer Partnerships',
    description: 'Built and managed ongoing micro-influencer ambassador program with 50 food and lifestyle creators.',
    thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop',
    results: ['200+ pieces of UGC', '2M+ impressions monthly', '3x ROI'],
    year: 2024,
  },
  {
    id: 'influencer-3',
    title: 'Celebrity Partnership',
    client: 'Elite Fitness',
    category: 'Influencer Partnerships',
    description: 'Secured and managed year-long partnership with celebrity athlete, including content creation and media appearances.',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=700&fit=crop',
    results: ['$2M+ media value', 'National TV appearances', 'Sold-out product line'],
    year: 2023,
  },
  // Events
  {
    id: 'events-1',
    title: 'Product Launch Event',
    client: 'Nova Electronics',
    category: 'Events',
    description: 'Produced high-profile product launch event with 300+ attendees including press, influencers, and VIP clients.',
    thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=500&fit=crop',
    results: ['300+ attendees', '75 media attendees', 'Trending on Twitter'],
    year: 2024,
  },
  {
    id: 'events-2',
    title: 'Press Preview Experience',
    client: 'Wanderlust Hotels',
    category: 'Events',
    description: 'Organized exclusive 3-day press trip for travel journalists and influencers at new resort property.',
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=800&fit=crop',
    results: ['25 journalists hosted', '40+ articles published', 'Condé Nast Traveler feature'],
    year: 2024,
  },
  {
    id: 'events-3',
    title: 'Pop-Up Activation',
    client: 'Urban Brew Coffee',
    category: 'Events',
    description: 'Designed and executed Instagram-worthy pop-up experience generating organic social buzz and media coverage.',
    thumbnail: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&h=600&fit=crop',
    results: ['5,000+ visitors', '10K+ social mentions', 'Food & Wine coverage'],
    year: 2023,
  },
]

export const categories = ['All', 'Digital', 'Print', 'Social', 'Influencer Partnerships', 'Events'] as const
